// Every player-visible string, in pt-BR. Components read text from here by key
// so a second locale can be added without touching them.
export const strings = {
  crash: {
    title: "Algo deu errado",
    body: "O jogo encontrou um erro e foi pausado.",
    reload: "Recarregar",
    exportSave: "Exportar save",
    exported: "Save copiado para a área de transferência",
    exportFailed: "Não foi possível copiar o save",
  },
  // Node names, on the cards and in the palette.
  nodes: {
    core: "Núcleo",
    extractor: "Extrator",
    furnace: "Fornalha",
    "assembler-1": "Montadora 1",
    generator: "Gerador",
    box: "Caixa",
    splitter: "Divisor",
    merger: "Mesclador",
    lab: "Laboratório",
    station: "Estação",
  },
  // Short item names, for costs.
  items: {
    "iron-ore": "minério de ferro",
    "copper-ore": "minério de cobre",
    coal: "carvão",
    stone: "pedra",
    "crude-oil": "petróleo",
    "iron-plate": "placa de ferro",
    "copper-plate": "placa de cobre",
    brick: "tijolo",
    gear: "engrenagem",
    "copper-cable": "fio de cobre",
    circuit: "circuito",
    rail: "trilho",
    "red-science": "ciência vermelha",
  },
  // The HUD capsule at the top of the screen.
  hud: {
    stock: "Estoque",
    emptyStock: "Estoque vazio",
    stamina: "Fôlego",
    power: "Energia",
    powerUse: "uso",
    powerShort: "falta de energia",
    powerGlyph: "⚡",
  },
  // The node palette: the "+" button, the bottom tray and placement feedback.
  palette: {
    open: "Construir",
    close: "Fechar paleta",
    free: "grátis",
  },
  // The edge menu, opened by tapping an edge, and the dragged edge's chip.
  edge: {
    title: "Aresta",
    level: "Nível",
    length: "células",
    upgrade: "Melhorar para nível",
    maxLevel: "Nível máximo",
    remove: "Remover",
    refund: "devolve",
    close: "Fechar",
    closeGlyph: "×",
    separator: " · ",
    tooLong: "Longa demais",
    onWater: "Cruza a água",
  },
  // Why a command was refused, shown as a hint.
  reasons: {
    connector_taken: "Conector já ligado",
    crosses_edge: "Cruza uma aresta",
    crosses_node: "Atravessa um nó",
    indestructible: "O Núcleo não pode ser removido",
    locked: "Ainda não pesquisado",
    max_level: "Já está no nível máximo",
    needs_deposit: "O Extrator precisa ficar sobre uma jazida",
    no_route: "Sem rota",
    no_stamina: "Sem fôlego",
    no_stock: "Estoque insuficiente",
    no_target: "Solte sobre uma entrada",
    not_found: "Não encontrado",
    not_tappable: "Petróleo não se coleta à mão",
    nothing_to_undo: "Nada para desfazer",
    occupied: "Espaço ocupado",
    on_deposit: "Só o Extrator fica sobre jazidas",
    on_water: "Não dá para construir na água",
    out_of_bounds: "Fora da área revelada",
    out_of_range: "Fora do limite",
    same_node: "Ligue a outro nó",
    storage_full: "O Núcleo está cheio",
    wrong_recipe: "Esta receita não roda neste nó",
  },
  // The rendering stress-test page (stress.html), used on real phones.
  stress: {
    items: "Itens",
    trains: "Trens",
    lod: "LOD",
    on: "ligado",
    off: "desligado",
    loseContext: "Forçar perda de contexto",
    contextLost: "contexto perdido",
    contextRestored: "contexto recuperado",
    copy: "copiar resultados",
    copied: "Resultados copiados",
    copyFailed: "Não foi possível copiar; selecione o texto abaixo",
    noWebgl: "Este teste precisa de WebGL, indisponível neste navegador.",
    hide: "ocultar",
    show: "mostrar",
  },
  // The debug tools (?debug=1 or a dev build): performance overlay and the
  // superadmin panel.
  debug: {
    admin: "admin",
    close: "fechar",
    seed: "Seed",
    regenerate: "Regenerar",
    speed: "Velocidade",
    teleport: "Teleportar",
    go: "Ir",
    revealRing: "Anel revelado",
    giveItems: "+100 de cada item",
    overlays: "Overlays",
    coreRings: "Anéis de depósito e raios de garantia",
    hashBuckets: "Baldes do hash espacial",
    powerMeshes: "Malhas de energia",
    nodes: "nós",
    edges: "arestas",
    items: "itens",
    trains: "trens",
    tick: "tick",
    render: "render",
    heap: "heap",
    notAvailable: "n/d",
  },
} as const;
