// Every player-visible string, in pt-BR. Components read text from here by key
// so a second locale can be added without touching them.
export const strings = {
  crash: {
    title: "Algo deu errado",
    body: "O jogo encontrou um erro e foi pausado.",
    reload: "Recarregar",
  },
  // The save's export and import, in the settings menu (FR128).
  save: {
    export: "Exportar save",
    exported: "Save copiado para a área de transferência",
    exportFailed: "Não foi possível exportar o save",
    copyByHand: "Não foi possível copiar: selecione e copie o texto abaixo",
    exportText: "Save exportado",
    import: "Importar save",
    importNote: "Cole um save exportado. Ele substitui a partida atual.",
    importText: "Save para importar",
    load: "Carregar save",
  },
  // Shown at boot when the latest save fails to load (FR129).
  backup: {
    title: "O save não pôde ser lido",
    body: "Há um backup do save anterior. Carregá-lo?",
    noBackup: "Não há backup. A partida recomeça do zero.",
    load: "Carregar backup",
    newGame: "Começar do zero",
  },
  // On iOS inside itch.io, where Safari may drop the save (NFR14).
  exportNotice: {
    body: "No iPhone e no iPad, o Safari pode apagar o save. Exporte-o de vez em quando.",
    export: "Exportar",
    dismiss: "Entendi",
  },
  // Node names, on the cards and in the palette.
  nodes: {
    core: "Núcleo",
    extractor: "Extrator",
    furnace: "Fornalha",
    "assembler-1": "Montadora 1",
    "assembler-2": "Montadora 2",
    generator: "Gerador",
    box: "Caixa",
    splitter: "Divisor",
    merger: "Mesclador",
    lab: "Laboratório",
    station: "Estação",
  },
  // A node's state, on the pill under its card (FR149).
  nodeStatus: {
    blocked: "Bloqueado",
    starved: "Sem insumos",
    no_power: "Sem energia",
  },
  // Short item names, for costs.
  items: {
    "iron-ore": "minério de ferro",
    "copper-ore": "minério de cobre",
    coal: "carvão",
    stone: "pedra",
    "crude-oil": "petróleo",
    "iron-plate": "placa de ferro",
    "copper-plate": "placa de cobre",
    brick: "tijolo",
    gear: "engrenagem",
    "copper-cable": "fio de cobre",
    circuit: "circuito",
    rail: "trilho",
    "red-science": "ciência vermelha",
  },
  // The HUD capsule at the top of the screen.
  hud: {
    stock: "Estoque",
    emptyStock: "Estoque vazio",
    stamina: "Fôlego",
    power: "Energia",
    powerUse: "uso",
    powerShort: "falta de energia",
    powerGlyph: "⚡",
    storageFull: "Estoque cheio: a fábrica parou",
  },
  // The node palette: the "+" button, the bottom tray and placement feedback.
  palette: {
    open: "Construir",
    close: "Fechar paleta",
    free: "grátis",
  },
  // What the node and edge menus share.
  menu: {
    maxLevel: "Nível máximo",
    remove: "Remover",
    refund: "devolve",
    close: "Fechar",
    closeGlyph: "×",
    separator: " · ",
  },
  // The edge menu, opened by tapping an edge, and the dragged edge's chip.
  edge: {
    title: "Aresta",
    level: "Nível",
    length: "células",
    upgrade: "Melhorar para nível",
    tooLong: "Longa demais",
    onWater: "Cruza a água",
  },
  // The node menu, opened by tapping a node.
  node: {
    title: "Nó",
    recipe: "Receita",
    autoRecipe: "Automática",
    recipeLoses: "Trocar a receita perde os itens dentro do nó",
    upgrade: "Melhorar para",
    full: "lotado",
    noConstruction: "Não usar em construção",
    used: "Desligado: a construção pode usar estes itens",
    kept: "Ligado: a construção não toca nesta Caixa",
  },
  // The research button and panel, and the notices of completed research.
  research: {
    glyph: "⚗",
    title: "Pesquisa",
    none: "Nenhuma pesquisa ativa: escolha uma",
    done: "Concluída",
    requires: "Requer",
    unlocks: "Libera",
    packs: "pacotes",
    tap: "toque rende",
    items: "itens",
    edge: "aresta nível",
    boxCapacity: "Caixa guarda",
    nothing: "nada: é o fim do protótipo",
    completed: "Pesquisa concluída",
    endTitle: "Fim do conteúdo do protótipo",
    endBody:
      "Você concluiu o Protótipo final. O jogo continua aberto: a fábrica segue rodando.",
    endClose: "Continuar",
    names: {
      "splitter-merger": "Divisor e Mesclador",
      "tools-1": "Ferramentas I",
      "tools-2": "Ferramentas II",
      "extra-boxes": "Caixas extras",
      "edge-2": "Aresta 2",
      railway: "Ferrovia",
      "final-prototype": "Protótipo final",
    },
  },
  // The onboarding hints (FR139), each in a capsule pointing at its target.
  hints: {
    "tap-deposit": "Toque no ferro para minerar",
    "place-extractor": "Construa um Extrator sobre uma jazida",
    "connect-core": "Arraste da saída até o Núcleo",
  },
  // The settings button and menu.
  settings: {
    title: "Ajustes",
    glyph: "⚙",
    reviewHints: "Rever dicas",
  },
  // The undo button.
  undo: {
    label: "Desfazer",
    glyph: "↶",
  },
  // Why a command was refused, shown as a hint.
  reasons: {
    bad_replay: "Replay inválido",
    bad_save: "Save inválido",
    connector_taken: "Conector já ligado",
    crosses_edge: "Cruza uma aresta",
    crosses_node: "Atravessa um nó",
    immovable: "O Núcleo não pode ser movido",
    indestructible: "O Núcleo não pode ser removido",
    locked: "Ainda não pesquisado",
    max_level: "Já está no nível máximo",
    needs_deposit: "O Extrator precisa ficar sobre uma jazida",
    newer_save: "Save de uma versão mais nova do jogo",
    no_route: "Sem rota",
    no_stamina: "Sem fôlego",
    no_stock: "Estoque insuficiente",
    no_target: "Solte sobre uma entrada",
    not_found: "Não encontrado",
    not_tappable: "Petróleo não se coleta à mão",
    nothing_to_undo: "Nada para desfazer",
    occupied: "Espaço ocupado",
    on_deposit: "Só o Extrator fica sobre jazidas",
    on_water: "Não dá para construir na água",
    out_of_bounds: "Fora da área revelada",
    out_of_range: "Fora do limite",
    researched: "Já pesquisado",
    same_node: "Ligue a outro nó",
    storage_full: "O Núcleo está cheio",
    wrong_recipe: "Esta receita não roda neste nó",
  },
  // The rendering stress-test page (stress.html), used on real phones.
  stress: {
    items: "Itens",
    trains: "Trens",
    lod: "LOD",
    on: "ligado",
    off: "desligado",
    loseContext: "Forçar perda de contexto",
    contextLost: "contexto perdido",
    contextRestored: "contexto recuperado",
    copy: "copiar resultados",
    copied: "Resultados copiados",
    copyFailed: "Não foi possível copiar; selecione o texto abaixo",
    noWebgl: "Este teste precisa de WebGL, indisponível neste navegador.",
    hide: "ocultar",
    show: "mostrar",
  },
  // The debug tools (?debug=1 or a dev build): performance overlay and the
  // superadmin panel.
  debug: {
    admin: "admin",
    close: "fechar",
    seed: "Seed",
    regenerate: "Regenerar",
    speed: "Velocidade",
    teleport: "Teleportar",
    go: "Ir",
    revealRing: "Anel revelado",
    giveItems: "+100 de cada item",
    replay: "Replay",
    exportReplay: "Exportar",
    loadReplay: "Carregar",
    overlays: "Overlays",
    coreRings: "Anéis de depósito e raios de garantia",
    hashBuckets: "Baldes do hash espacial",
    powerMeshes: "Malhas de energia",
    nodes: "nós",
    edges: "arestas",
    items: "itens",
    trains: "trens",
    tick: "tick",
    render: "render",
    heap: "heap",
    notAvailable: "n/d",
  },
} as const;
